In [3]:
from PIL import Image
import numpy as np
import os

<b>Check which texture image is failing and is greyscale</b>

In [39]:
# Train Visible Images
os.chdir("/home/local/AD/cordun1/experiments/causality/counterfactual_generative_networks/mnists")


def process_iris(mypath):
    dirs = os.listdir(mypath)
    counter = 0
    for item in dirs:
        print(item)
        fullpath = os.path.join(mypath, item)
        print(fullpath)
        if os.path.isfile(os.path.join(fullpath)):
            counter += 1
            im = Image.open(fullpath)
            print("image opened")
            arr = Image.fromarray(np.uint8(im))
            print(arr)
            print(arr.size)
            #print(arr.shape)
            print(counter)
        counter+=1


<b>Original Textures Directory from the Repo</b>

In [40]:
path = "./data/textures_OG/background/" 
process_iris(path)

3_veined_0180.jpg
./data/textures_OG/background/3_veined_0180.jpg
image opened
<PIL.Image.Image image mode=RGB size=640x492 at 0x7F5DE465EC90>
(640, 492)
1
5_veined_0157.jpg
./data/textures_OG/background/5_veined_0157.jpg
image opened
<PIL.Image.Image image mode=RGB size=491x501 at 0x7F5DE465E190>
(491, 501)
3
7_veined_0104.jpg
./data/textures_OG/background/7_veined_0104.jpg
image opened
<PIL.Image.Image image mode=RGB size=560x533 at 0x7F5DE47FE950>
(560, 533)
5
1_veined_0067.jpg
./data/textures_OG/background/1_veined_0067.jpg
image opened
<PIL.Image.Image image mode=RGB size=512x512 at 0x7F5DE465E910>
(512, 512)
7
2_veined_0073.jpg
./data/textures_OG/background/2_veined_0073.jpg
image opened
<PIL.Image.Image image mode=RGB size=339x400 at 0x7F5DE465E3D0>
(339, 400)
9
6_veined_0158.jpg
./data/textures_OG/background/6_veined_0158.jpg
image opened
<PIL.Image.Image image mode=RGB size=502x412 at 0x7F5DE465E990>
(502, 412)
11
.ipynb_checkpoints
./data/textures_OG/background/.ipynb_checkpo

In [41]:
path = "./data/textures_OG/object/" 
process_iris(path)

6_striped_0097.jpg
./data/textures_OG/object/6_striped_0097.jpg
image opened
<PIL.Image.Image image mode=RGB size=640x516 at 0x7F5DE4809A50>
(640, 516)
1
8_striped_0125.jpg
./data/textures_OG/object/8_striped_0125.jpg
image opened
<PIL.Image.Image image mode=RGB size=410x304 at 0x7F5DE465EA90>
(410, 304)
3
7_striped_0004.jpg
./data/textures_OG/object/7_striped_0004.jpg
image opened
<PIL.Image.Image image mode=RGB size=418x300 at 0x7F5DE465E3D0>
(418, 300)
5
3_striped_0043.jpg
./data/textures_OG/object/3_striped_0043.jpg
image opened
<PIL.Image.Image image mode=RGB size=640x412 at 0x7F5DE465EA90>
(640, 412)
7
5_striped_0028.jpg
./data/textures_OG/object/5_striped_0028.jpg
image opened
<PIL.Image.Image image mode=RGB size=398x374 at 0x7F5DE465E0D0>
(398, 374)
9
9_striped_0033.jpg
./data/textures_OG/object/9_striped_0033.jpg
image opened
<PIL.Image.Image image mode=RGB size=640x480 at 0x7F5DE465EA90>
(640, 480)
11
0_striped_0001.jpg
./data/textures_OG/object/0_striped_0001.jpg
image opene

<b>Check my personal textures - which one is failing?</b>

Make sure mod is not 'L', make sure there are no hidden .ipynb_checkpoint files

In [46]:
path = "./data/textures/background/" 
process_iris(path)

6_BG.jpg
./data/textures/background/6_BG.jpg
image opened
<PIL.Image.Image image mode=RGB size=368x368 at 0x7F5DE47F8B10>
(368, 368)
1
1_BG.jpg
./data/textures/background/1_BG.jpg
image opened
<PIL.Image.Image image mode=RGB size=626x414 at 0x7F5DE48B2950>
(626, 414)
3
5_BG.jpg
./data/textures/background/5_BG.jpg
image opened
<PIL.Image.Image image mode=RGB size=4000x3000 at 0x7F5DE47F8B50>
(4000, 3000)
5
2_BG.jpg
./data/textures/background/2_BG.jpg
image opened
<PIL.Image.Image image mode=RGB size=2500x1667 at 0x7F5DE47EDE90>
(2500, 1667)
7
4_BG.jpg
./data/textures/background/4_BG.jpg
image opened
<PIL.Image.Image image mode=RGB size=600x400 at 0x7F5DE47EDCD0>
(600, 400)
9
8_BG.jpg
./data/textures/background/8_BG.jpg
image opened
<PIL.Image.Image image mode=RGB size=2800x2200 at 0x7F5DE47EDDD0>
(2800, 2200)
11
7_BG.jpg
./data/textures/background/7_BG.jpg
image opened
<PIL.Image.Image image mode=RGB size=800x534 at 0x7F5DE47F8050>
(800, 534)
13
3_BG.jpg
./data/textures/background/3_BG.

In [50]:
path = "./data/textures/object/" 
process_iris(path)

4_OB.jpg
./data/textures/object/4_OB.jpg
image opened
<PIL.Image.Image image mode=RGB size=600x400 at 0x7F5DE466B0D0>
(600, 400)
1
1_OB.jpg
./data/textures/object/1_OB.jpg
image opened
<PIL.Image.Image image mode=RGB size=3072x2048 at 0x7F5DE487DB10>
(3072, 2048)
3
5_OB.jpg
./data/textures/object/5_OB.jpg
image opened
<PIL.Image.Image image mode=RGB size=326x300 at 0x7F5DE466B8D0>
(326, 300)
5
2_OB.jpg
./data/textures/object/2_OB.jpg
image opened
<PIL.Image.Image image mode=RGB size=1200x907 at 0x7F5DE466BA90>
(1200, 907)
7
6_OB.jpg
./data/textures/object/6_OB.jpg
image opened
<PIL.Image.Image image mode=RGB size=5009x2642 at 0x7F5DE487DB10>
(5009, 2642)
9
9_OB.jpg
./data/textures/object/9_OB.jpg
image opened
<PIL.Image.Image image mode=RGB size=512x320 at 0x7F5DE466B8D0>
(512, 320)
11
0_OB.jpg
./data/textures/object/0_OB.jpg
image opened
<PIL.Image.Image image mode=RGB size=1200x733 at 0x7F5DE466B2D0>
(1200, 733)
13
3_OB.jpg
./data/textures/object/3_OB.jpg
image opened
<PIL.Image.Imag

<b>How to create a Tensordataset</b>

In [92]:
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd

In [93]:
from numpy import asarray
import pandas as pd

def make_test_tensor(path, csv):
    # Get the test labels, there should be 105 
    df = pd.read_csv(csv, header=None)
    df = df[1:]
    labels = df[1].values
    labels = labels.astype(int)
    test_labels = labels[945:]
    print("len test_labels:", len(test_labels))
    
    # Read in images as arrays
    test_images = []
    dirs = os.listdir(path)
    for item in dirs:
        #print(item)
        fullpath = os.path.join(path, item)
        #print(fullpath)
        if os.path.isfile(os.path.join(fullpath)):
            im = Image.open(fullpath)
            #print("image opened")
            numpydata = asarray(im)
            #arr = Image.fromarray(np.uint8(im))
            #print(arr)
            #print(arr.size)
            test_images.append(numpydata)
    print("len test images:", len(test_images))
    tensor_x = torch.Tensor(test_images) # transform to torch tensor
    tensor_y = torch.Tensor(test_labels)

    my_dataset = TensorDataset(tensor_x,tensor_y) # create your datset
    
    return my_dataset
    
    
    
    

In [94]:
test_root = "/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test"
annots_csv = "/home/local/AD/cordun1/experiments/data/labels/Eur_labels2_cfg.csv"

In [95]:
# use the function
ds_test = make_test_tensor(path = test_root, csv = annots_csv)

len test_labels: 105


In [96]:
ds_test

In [75]:
df = pd.read_csv(annots_csv, header=None)

df = df[1:]


0  1
1      1_003_1_01_NN.bmp  0
2      1_003_1_02_EH.bmp  1
3      1_003_1_03_EA.bmp  1
4      1_003_1_04_ES.bmp  1
5     1_003_1_05_ESp.bmp  2
...                  ... ..
1046  1_036_1_17_LLU.bmp  9
1047  1_036_1_18_LLR.bmp  9
1048  1_036_1_19_LLL.bmp  9
1049   1_036_1_20_LD.bmp  9
1050   1_036_1_21_LR.bmp  9

[1050 rows x 2 columns]

In [82]:
labels = df[1].values
labels = labels.astype(int)
print(type(labels))

<class 'numpy.ndarray'>


In [83]:
labels

array([0, 1, 1, ..., 9, 9, 9])

In [60]:
from numpy import asarray

In [63]:
# Convert images in root to a numpy array

def images_to_array(mypath):
    images = []
    dirs = os.listdir(mypath)
    for item in dirs:
        print(item)
        fullpath = os.path.join(mypath, item)
        print(fullpath)
        if os.path.isfile(os.path.join(fullpath)):
            im = Image.open(fullpath)
            print("image opened")
            numpydata = asarray(im)
            #arr = Image.fromarray(np.uint8(im))
            #print(arr)
            #print(arr.size)
            images.append(numpydata)
    #print(images)         
    return images


In [64]:
# Test images - list of images in array

test = images_to_array(test_root)

1_001_1_01_NN_real_B.png
/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test/1_001_1_01_NN_real_B.png
image opened
1_021_1_04_ES_real_B.png
/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test/1_021_1_04_ES_real_B.png
image opened
1_031_1_16_OHM_real_B.png
/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test/1_031_1_16_OHM_real_B.png
image opened
1_021_1_11_PR_real_B.png
/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test/1_021_1_11_PR_real_B.png
image opened
1_002_1_16_OHM_real_B.png
/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test/1_002_1_16_OHM_real_B.png
image opened
1_021_1_14_OH_real_B.png
/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test/1_021_1_14_OH_real_B.png
image opened
1_021_1_01_NN_real_B.png
/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test/1_021_1_01_NN_real_B.png
image opened
1_031_1_07_AOM_real_B.png
/home/local/AD/cordun1/experiments/data/Eurecom_Thermal/test/1_031_1_07_AOM_real_B.png
image opened
1_

In [65]:
len(test)

105

In [66]:
test[0]

array([[[30, 30, 30],
        [30, 30, 30],
        [30, 30, 30],
        ...,
        [23, 23, 23],
        [24, 24, 24],
        [24, 24, 24]],

       [[30, 30, 30],
        [30, 30, 30],
        [30, 30, 30],
        ...,
        [23, 23, 23],
        [24, 24, 24],
        [24, 24, 24]],

       [[31, 31, 31],
        [31, 31, 31],
        [29, 29, 29],
        ...,
        [19, 19, 19],
        [19, 19, 19],
        [19, 19, 19]],

       ...,

       [[19, 19, 19],
        [19, 19, 19],
        [18, 18, 18],
        ...,
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

In [79]:
type(labels)

numpy.ndarray

In [85]:
labels

array([0, 1, 1, ..., 9, 9, 9])

In [86]:
len(labels)

1050

In [90]:
test_labels = labels[945:]
len(test_labels)

105

In [89]:
df[945:]

0  1
946    1_001_1_01_NN.bmp  0
947    1_001_1_02_EH.bmp  1
948    1_001_1_03_EA.bmp  1
949    1_001_1_04_ES.bmp  1
950   1_001_1_05_ESp.bmp  2
...                  ... ..
1046  1_036_1_17_LLU.bmp  9
1047  1_036_1_18_LLR.bmp  9
1048  1_036_1_19_LLL.bmp  9
1049   1_036_1_20_LD.bmp  9
1050   1_036_1_21_LR.bmp  9

[105 rows x 2 columns]

In [91]:
tensor_x = torch.Tensor(test) # transform to torch tensor
tensor_y = torch.Tensor(test_labels)

my_dataset = TensorDataset(tensor_x,tensor_y) # create your datset